### ISSUE TITLE
Application should run using https

### ISSUE THREAD

**Issue by benlangfeld** [Flaredown/FlaredownEmber-2#449]
http://app.flaredown.com has no TLS configured. Should be a simple configuration in Heroku to issue Let's Encrypt certs.

**Comment by bklang** [comment]
I am able to access `https://app.flaredown.com`. However visiting https://flaredown.com and clicking the "Log in here" link directs the user to `http://app.flaredown.com/login`. When we fix this, we should ensure that requests to the non-https url are redirected to the secured one.

**Comment by bklang** [comment]
When trying to log in via https, the user sees a full-page refresh upon submitting their login credentials. The POST to create a session appears to work, but then for some reason the page refreshes, putting them back on the login screen. Switching to http only, the user was able to log in.

**Comment by benlangfeld** [comment]
Closed by https://github.com/rubyforgood/Flaredown/pull/498
