### ISSUE TITLE
Unable to create accounts in the staging environment

### ISSUE THREAD

**Issue by bklang** [Flaredown/FlaredownEmber-2#451]
See screenshot: error with Captcha makes it impossible to submit form
<img width="554" alt="Screen Shot 2021-10-11 at 2 43 33 PM" src="https://user-images.githubusercontent.com/167131/136839125-7bdfedae-808a-412c-b3c5-d8a5d394b75a.png">

**Comment by bklang** [comment]
This appears to be user error. I followed the link from the Heroku dashboard, which takes me to `https://flaredown-staging-webapp.herokuapp.com/signup`. The captcha works fine when using the correct staging url, `http://staging.flaredown.com/signup`

**Comment by compwron** [comment]
discussed in slack, now Ben L has access, and it *may* be fixed?

**Comment by compwron** [comment]
nice
