### ISSUE TITLE
Modern Heroku stack

### ISSUE THREAD

**Issue by benlangfeld** [Flaredown/FlaredownEmber-2#454]
flaredown-staging-api: heroku-18
flaredown-staging-webapp: heroku-20

The README states that Cedar-14 is in use and needs upgrading, but I'm not sure where.

**Comment by benlangfeld** [comment]
@compwron @lmerriam could you help me understand the current state of production and what upgrades are desired? I guess we want a heroku-20 upgrade all round. Is anything actually still using Cedar-14, or is the README out of date?

**Comment by compwron** [comment]
we got rid of heroku cedar-14 during the prod deploy last week, thank goodness

**Comment by compwron** [comment]
readme is out of date

**Comment by benlangfeld** [comment]
I upgraded flaredown-staging-api to heroku-20. @codemonium will fix the README.

**Comment by benlangfeld** [comment]
It looks like we got ahead of ourselves with the heroku-20 upgrade of flaredown-staging-api:

```
 !     The Ruby version you are trying to install does not exist on this stack.
 !     
 !     You are trying to install ruby-2.6.5 on heroku-20.
 !     
 !     Ruby ruby-2.6.5 is present on the following stacks:
 !     
 !     - heroku-18
```

It seems we need to upgrade to [ruby 2.6.8](https://devcenter.heroku.com/articles/ruby-support#ruby-versions).
